version: 2.0
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: Save test results
          command: |
           gradle jar
          when: always
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results/junit
