version: 2.0
jobs:
  tests:
    docker:
     - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: gradle test
      - store_test_results:
          path: test-results
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle Run
          command: gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
  
workflows:
  version: 2
  job_flow:
    jobs:
      - tests
      - package:
          requires:
            - tests
    