version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle test
      - store_test_results:
         path: /mnt/c/Users/jo-be/code/circle-ci-workshop/test-result/
