version: 2.0
jobs:
  test:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: Save test results
          command: gradle test

      - store_test_results:
          path: build/test-results 
      
  jar:
     docker:
    - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: run jar
          command: gradle jar
      - store_artifacts:
            path: /code/test-results
            destination: prefix
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - jar:
            requires:
            - test