version: 2.0
jobs:
  test:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: Save test results
          command: |
          gradle test
          
          when: always
      - store_test_results:
          path: build/test-results 
      
    build:
     docker:
    - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: Save test results
          command: |
           gradle jar
          when: always
      - store_artifacts:
          path: build/libs
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - build